FROM node:12

ENV TARGET_FOLDER_NAME="ePI-workspace"
RUN git clone https://github.com/PharmaLedger-IMI/epi-workspace.git $TARGET_FOLDER_NAME

RUN cd $TARGET_FOLDER_NAME && \
    npm install --unsafe-perm

RUN cd $TARGET_FOLDER_NAME && \
    npm run build privatesky

RUN cd $TARGET_FOLDER_NAME/ethadapter/EthAdapter && \
    npm install --unsafe-perm

WORKDIR /$TARGET_FOLDER_NAME/ethadapter/EthAdapter

EXPOSE 3000

CMD [ "node" , "index.js" ]
